#!/bin/sh
set -eu

if ! git diff --quiet -- '*.go' go.sum go.mod; then
	echo "Go files have unstage changes"
	exit 1
fi

unformatted="$(gofmt -l .)"

if [ -n "$unformatted" ]; then
	echo "formatting failed"
	echo "$unformatted"
	exit 1
fi

go vet ./...
go test ./...
